VCPath="D:\Programme\Visual Studio 2013\VC\bin"

PandoreLibPath=C:\pandore\lib
PandoreIncludePath=C:\pandore\include

IntelTBBIncludePath=C:\IntelTBB\include
IntelTBBLibPath=C:\IntelTBB\bin\mingw32

OpenCLIncludePath="C:\Program Files\NVIDIA GPU Computing Toolkit\NVIDIA GPU Computing SDK\OpenCL\common\inc"
OpenCLLibPath="C:\Program Files\NVIDIA GPU Computing Toolkit\NVIDIA GPU Computing SDK\OpenCL\common\lib\Win32"
